server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:9002/
          predicates:
            - Path=/auth/**

        - id: songs
          uri: http://localhost:9001/
          predicates:
            - Path=/songs/**

        - id: group
          uri: http://localhost:9003/
          predicates:
            - Path=/group/**
            - Path=/group/news/**
